package com.example.ishop.model;

public enum ScreenNames {

    MAIN_SCREEN, PRODUCT_SCREEN, LOGIN_PAGE_SCREEN, CREATE_ACCOUNT_PAGE_SCREEN, PRIVATE_ACCOUNT_SCREEN, CART_PAGE_SCREEN, VENDOR_PAGE_SCREEN
}
